name: iOS distribution

on: workflow_dispatch
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    name: Archive and export build to the firebase
    runs-on: macos-latest

    steps:
      - name: Install firebase
        run: |
          npm install -g firebase-tools
      - name: Update GoogleInfo
        run: |
          /usr/libexec/PlistBuddy -c "Set API_KEY ${{ secrets.FIREBASE_KEY }}" beBetter/Resources/GoogleService-Info.plist
      - name: Archive build
        run: |
          xcodebuild archive -scheme beBetter -sdk iphoneos -allowProvisioningUpdates -archivePath beBetter.xcarchive
      - name: Firebase login 
        run: |
          firebase projects:list --token "${{ secrets.FIREBASE_ACCESS_TOKEN }}"

