name: iOS distribution

on: workflow_dispatch
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Update GoogleInfo
        run: |
          ls
      - name: Set Default Scheme
        run: |
          default=$(echo beBetter)
