name: iOS distribution

on: workflow_dispatch
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    name: Archive and export build to the firebase
    runs-on: macos-latest

    steps:
      - name: Firebase login 
        run: |
          firebase login:ci
